CREATE TABLE Courses(
   ID_Course   VARCHAR(6) NOT NULL PRIMARY KEY
  ,Course_Name VARCHAR(100) NOT NULL
  ,Lecturer    VARCHAR(50) NOT NULL
  ,Topic       VARCHAR(50) NOT NULL
  ,Attendance  INTEGER  NOT NULL
);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('II2110','Matematika STI','I Gusti Bagus Baskara Nugraha','Sistem dan Teknologi Informasi',54);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('II2111','Probabilitas dan Statistik','Dimitri Mahayana','Sistem dan Teknologi Informasi',53);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('II3120','Layanan STI','Suhardi','Sistem dan Teknologi Informasi',46);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('II3121','Analisis Kebutuhan Enterprise','Kridanto Surendro','Sistem dan Teknologi Informasi',45);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('II3130','Sistem Operasi','Albarda','Sistem dan Teknologi Informasi',49);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('II3150','Sistem Multimedia','Yusep Rosmansyah','Sistem dan Teknologi Informasi',43);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('II3160','Pemrograman Integratif','I Gusti Bagus Baskara Nugraha','Sistem dan Teknologi Informasi',44);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('II4021','Sistem Pendukung Pengambilan Keputusan','Mary Handoko','Sistem dan Teknologi Informasi',20);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('II4022','Audit Teknologi Informasi','Kridanto Surendro','Sistem dan Teknologi Informasi',49);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('II4032','Analisis & Perancangan Kinerja Sistem','Achmad Imam Kistijantoro','Sistem dan Teknologi Informasi',47);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('II4033','Forensik Digital','Yusuf Kurniawan','Sistem dan Teknologi Informasi',16);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('II4071','Keprofesian STI','Suhono Harso Supangkat','Sistem dan Teknologi Informasi',50);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('II4470','Hukum & Etika Teknologi Informasi','Dicky Prima Satya','Sistem dan Teknologi Informasi',52);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('II4471','Kapita Selekta STI','Arry Achmad Arman','Sistem dan Teknologi Informasi',53);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EB2101','Dasar Teknik Biomedis','Agung Wahyu Setiawan','Teknik Biomedis',37);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EB2102','Rangkaian Elektrik dan Elektronika','Achmad Fuad Mas''ud','Teknik Biomedis',37);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EB2103','Anatomi dan Fisiologi I','Richard Karel Willem Mengko','Teknik Biomedis',30);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EB3104','Biomekanika','Tati Latifah Erawati Rajab','Teknik Biomedis',29);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EB3108','Probabilitas dan Biostatistika','Andriyan Bayu Suksmono','Teknik Biomedis',31);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EP2091','Probabilitas & Statistik','Ngapuli Irmea Sinisuka','Teknik Tenaga Listrik',35);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EP2274','Teknik Tenaga Listrik','Burhanuddin Halimi','Teknik Tenaga Listrik',147);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EP3071','Mesin-mesin Listrik','Agus Purwadi','Teknik Tenaga Listrik',34);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EP3073','Analisis Numerik Untuk Tenaga Listrik','Deny Hamdani','Teknik Tenaga Listrik',42);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EP3075','Analisis Sistem Tenaga','Muhammad Nurdin','Teknik Tenaga Listrik',34);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EP3076','Proteksi Sistem Tenaga','Reynaldo Zoro','Teknik Tenaga Listrik',13);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EP3095','Material Elektroteknik','Suwarno','Teknik Tenaga Listrik',37);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EP4070','Desain Sistem Tenaga Listrik','Syarif Hidayat','Teknik Tenaga Listrik',27);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EP4071','Pemanfaatan Energi Listrik','Agus Purwadi','Teknik Tenaga Listrik',46);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EP4072','SCADA dan Manajemen Energi','Syarif Hidayat','Teknik Tenaga Listrik',28);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EP4073','Kapita Selekta Tenaga Listrik','Pekik Argo Dahono','Teknik Tenaga Listrik',45);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EP4077','Sistem Distribusi Tenaga Listrik','Arwindra Rizqiawan','Teknik Tenaga Listrik',46);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EP4079','Proteksi Rele','Nanang Hariyanto','Teknik Tenaga Listrik',8);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('ET2000','Medan Elektromagnetik I','Chairunnisa','Teknik Telekomunikasi',13);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('ET2001','Matematika Diskrit','Nana Rachmana Syambas','Teknik Telekomunikasi',33);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('ET2002','Probabilitas & Statistika','Andriyan Bayu Suksmono','Teknik Telekomunikasi',9);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('ET2003','Rangkaian Listrik','Mohammad Ridwan Effendi','Teknik Telekomunikasi',31);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('ET2004','Pengolahan Sinyal dalam waktu Kontinyu','Ian Josef Matheus Edward','Teknik Telekomunikasi',11);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('ET2005','Desain Sistem Digital','Nana Rachmana Syambas','Teknik Telekomunikasi',32);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('ET2007','Pemrograman','Hamonangan Situmorang','Teknik Telekomunikasi',33);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('ET3000','Medan Elektromagnetik II','Chairunnisa','Teknik Telekomunikasi',37);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('ET3001','Sistem Komunikasi Analog & Digital','Iskandar','Teknik Telekomunikasi',44);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('ET3002','Komunikasi Digital','Mohammad Sigit Arifianto','Teknik Telekomunikasi',6);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('ET3003','Jaringan Komputer','Tutun Juhana','Teknik Telekomunikasi',81);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('ET3004','Rekayasa Trafik Telekomunikasi','Sigit Haryadi','Teknik Telekomunikasi',42);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('ET3005','Pengolahan Sinyal dalam waktu Diskrit','Effrina Yanti Hamid','Teknik Telekomunikasi',34);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('ET3006','Elektronika Frekuensi Radio','Achmad Munir','Teknik Telekomunikasi',8);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('ET3007','Antena & Propagasi Gelombang','Adit Kurniawan','Teknik Telekomunikasi',8);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('ET3009','Rekayasa Perangkat Lunak','Hamonangan Situmorang','Teknik Telekomunikasi',40);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('ET3010','Layanan Tersambung & Komputasi Awan','Eueung Mulyana','Teknik Telekomunikasi',1);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('ET4003','Kapita Selekta Telekomunikasi','Mohammad Ridwan Effendi','Teknik Telekomunikasi',31);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('ET4040','Ekonomi, Bisnis, Regulasi dan Kebijakan Telekomunikasi','Sigit Haryadi','Teknik Telekomunikasi',17);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('ET4041','Sistem Komunikasi Multimedia','Hendrawan','Teknik Telekomunikasi',31);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('ET4042','Sistem Komunikasi Optik Non-Linier','Hardi Nusantara','Teknik Telekomunikasi',5);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('ET4044','Pemrograman Perangkat Telekomunikasi','Eueung Mulyana','Teknik Telekomunikasi',14);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('ET4058','Sistem Radar dan Navigasi','Joko Suryana','Teknik Telekomunikasi',6);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('ET4061','Jaringan Akses Nir-kabel','Adit Kurniawan','Teknik Telekomunikasi',32);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('ET4064','Sistem Komunikasi Satelit & Terestrial','Joko Suryana','Teknik Telekomunikasi',4);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('ET4144','Manajemen Jaringan Telekomunikasi','Ian Josef Matheus Edward','Teknik Telekomunikasi',5);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('ET4160','Manajemen Proyek Telekomunikasi','Hardi Nusantara','Teknik Telekomunikasi',23);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('ET4242','Teknologi IP Lanjut','Tutun Juhana','Teknik Telekomunikasi',18);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EL1200','Pengantar Analisis Rangkaian','Mervin Tangguar Hutabarat','Teknik Elektro',25);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EL2001','Rangkaian Elektrik','Eniman Yunus Syamsudin','Teknik Elektro',162);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EL2002','Sistem Digital','Yudi Satria Gondokaryono','Teknik Elektro',126);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EL2003','Struktur Diskrit','Yoga Priyana','Teknik Elektro',116);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EL2004','Probabilitas & Statistika','Dimitri Mahayana','Teknik Elektro',118);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EL2005','Elektronika','Elvayandri','Teknik Elektro',29);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EL2006','Medan Elektromagnetik','Bambang Anggoro Soedjarno P.','Teknik Elektro',89);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EL2007','Sinyal & Sistem','Widyawardana Adiprawita','Teknik Elektro',29);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EL2008','Pemecahan Masalah dengan C','Aciek Ida Wuryandari','Teknik Elektro',1);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EL2142','Sistem Digital & Mikroprosesor','Yusuf Kurniawan','Teknik Elektro',118);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EL3009','Elektronika II','Amy Hamidah Salman','Teknik Elektro',106);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EL3010','Pengolahan Sinyal Digital','Yoannes Bandung','Teknik Elektro',116);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EL3011','Arsitektur Sistem Komputer','Yudi Satria Gondokaryono','Teknik Elektro',106);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EL3012','Material Teknik Elektro','Irman Idris','Teknik Elektro',115);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EL3013','Sistem Instrumentasi','Arief Syaichu Rohman','Teknik Elektro',19);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EL3014','Sistem Mikroprosesor','Farkhad Ihsan Hariadi','Teknik Elektro',4);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EL3015','Sistem Kendali','Carmadi Machbub','Teknik Elektro',75);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EL3016','Sistem Komunikasi','Emir Mauludi Husni','Teknik Elektro',3);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EL3017','Sistem Tenaga Elektrik','Umar Khayam','Teknik Elektro',14);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EL4018','Etika Profesi & Rekayasa','Emir Mauludi Husni','Teknik Elektro',132);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EL4019','Sistem Penggerak Elektrik','Arief Syaichu Rohman','Teknik Elektro',35);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EL4120','Jaringan Komputer','Waskita Adijarto','Teknik Elektro',21);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EL4121','Perancangan Sistem Embedded','Waskita Adijarto','Teknik Elektro',20);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EL4123','Sistem Kendali Digital','Iyas Munawar','Teknik Elektro',22);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EL4125','Pengolahan Citra Digital','Tati Latifah Erawati Rajab','Teknik Elektro',62);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EL4126','Robotika','Hilwadi Hindersah','Teknik Elektro',97);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EL4127','Arsitektur & Komputasi Paralel','Yudi Satria Gondokaryono','Teknik Elektro',91);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EL4128','Perancangan Sistem Operasi','Yoga Priyana','Teknik Elektro',42);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EL4129','Devais Semikonduktor','Adang Suwandi Ahmad','Teknik Elektro',8);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EL4131','Anatomi dan Fisiologi','Richard Karel Willem Mengko','Teknik Elektro',23);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EL4132','Teknik Biomedika','Agung Wahyu Setiawan','Teknik Elektro',30);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EL4138','Perancangan Sistem VLSI','Trio Adiono','Teknik Elektro',20);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('EL4241','Mikroelektronika RF & Mixed Signal','Basuki Rachmatul Alam','Teknik Elektro',6);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('IF2110','Algoritma & Struktur Data','Adi Mulyanto','Teknik Informatika',165);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('IF2111','Algoritma dan Struktur Data','Riza Satria Perdana','Teknik Informatika',52);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('IF2120','Matematika Diskrit','Rinaldi','Teknik Informatika',163);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('IF2121','Logika Informatika','Nur Ulfa Maulidevi','Teknik Informatika',161);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('IF2123','Aljabar Geometri','Judhi Santoso','Teknik Informatika',164);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('IF2130','Organisasi & Arsitektur Komputer','Kusprasapta Mutijarsa','Teknik Informatika',162);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('IF2132','Pemrograman Komputer','Fazat Nur Azizah','Teknik Informatika',102);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('IF2140','Pemodelan Basis Data','Adi Mulyanto','Teknik Informatika',50);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('IF2220','Teori Bahasa Formal dan Otomata','Harlili','Teknik Informatika',156);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('IF3110','Pengembangan Aplikasi Berbasis Web','Riza Satria Perdana','Teknik Informatika',168);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('IF3111','Pengembangan Aplikasi pada Platform Khusus','Saiful Akbar','Teknik Informatika',44);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('IF3130','Jaringan Komputer','Afwarman','Teknik Informatika',147);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('IF3140','Manajemen Basis Data','Saiful Akbar','Teknik Informatika',157);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('IF3150','Manajemen Proyek Perangkat Lunak','Adi Mulyanto','Teknik Informatika',156);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('IF3151','Interaksi Manusia & Komputer','Dwi Hendratmo Widyantoro','Teknik Informatika',156);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('IF3152','Rekayasa Perangkat Lunak','Wikan Danar Sunindyo','Teknik Informatika',46);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('IF3170','Intelegensi Buatan','Ayu Purwarianti','Teknik Informatika',148);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('IF4031','Pengembangan Aplikasi Terdistribusi','Achmad Imam Kistijantoro','Teknik Informatika',54);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('IF4041','Teknologi Basis Data','Gusti Ayu Putri Saptawati S','Teknik Informatika',48);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('IF4043','Sistem Informasi Lanjut','Iping Supriana Suwardi','Teknik Informatika',35);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('IF4050','Pembangunan Perangkat Lunak Berorientasi Service','Bernhard Sitohang','Teknik Informatika',37);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('IF4070','Representasi Pengetahuan dan Penalaran','Iping Supriana Suwardi','Teknik Informatika',30);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('IF4071','Pembelajaran Mesin','Dessi Puji Lestari','Teknik Informatika',94);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('IF4072','Pemrosesan Text dan Suara Bahasa Alami','Ayu Purwarianti','Teknik Informatika',66);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('IF4073','Interpretasi dan Pengolahan Citra','Iping Supriana Suwardi','Teknik Informatika',20);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('IF4150','Rekayasa Perangkat Lunak Spesifik Domain','M.M. Inggriani','Teknik Informatika',110);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('KU1071','Pengenalan Teknologi Informasi A','Adi Mulyanto','Kuliah Umum',690);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('KU1072','Pengenalan Teknologi Informasi B','Fazat Nur Azizah','Kuliah Umum',1371);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('MS1100','Pengenalan Teknik Mesin, Material, dan Dirgantara','Arief Hariyanto','Teknik Mesin',98);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('MS1200','Gambar Teknik','Indria Herman','Teknik Mesin',1);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('MS1210','Statika Struktur','Abdul Hakim Masyhur','Teknik Mesin',1);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('MS2021','Mekanika Teknik Dasar','Muhamad Giri Suada','Teknik Mesin',131);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('MS2022','Pemilihan Elemen Mesin','M. Agus Kariem','Teknik Mesin',50);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('MS2041','Rekayasa Termal & Mekanika Fluida','Willy Adriansyah','Teknik Mesin',67);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('MS2100','Analisis Teknik Dasar','Nathanael Panagung Tandian','Teknik Mesin',269);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('MS2111','Mekanika Kekuatan Material','Sandro Mihradi','Teknik Mesin',289);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('MS2112','Kinematika dan Dinamika','Kemas Rifian','Teknik Mesin',198);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('MS2130','Termodinamika Teknik I','I Made Astina','Teknik Mesin',224);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('MS2150','Material Teknik','Bambang Widyanto','Teknik Mesin',330);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('MS2230','Termodinamika Teknik II','Toto Hardianto','Teknik Mesin',1);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('MS3051','Pemilihan Bahan dalam Desain','Firmansyah','Teknik Mesin',20);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('MS3100','Pengukuran Teknik','Zainal Abidin','Teknik Mesin',156);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('MS3110','Getaran Mekanik Dasar','Ignatius Pulung Nurprasetio','Teknik Mesin',155);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('MS3111','Elemen Mesin II','Bagus Budiwantoro','Teknik Mesin',150);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('MS3130','Perpindahan Panas I','Willy Adriansyah','Teknik Mesin',165);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('MS3131','Mekanika Fluida II','Priyono Soetikno','Teknik Mesin',119);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('MS3160','Proses Manufaktur II','Tri Prakosa','Teknik Mesin',162);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('MS3161','Metrologi Industri & Statistika','Agung Wibowo','Teknik Mesin',163);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('MS3181','Rangkaian Digital','Indrawanto','Teknik Mesin',20);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('MS3201','Manajemen & Ekonomi Kerekayasaan','Yatna Yuwana Martawirya','Teknik Mesin',119);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('MS4010','Teknik Kendaraan','Ignatius Pulung Nurprasetio','Teknik Mesin',14);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('MS4011','Metode Elemen Hingga','M. Agus Kariem','Teknik Mesin',11);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('MS4014','Perancangan dan Konstruksi Sistem Perpipaan','M. Agus Kariem','Teknik Mesin',18);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('MS4030','Sistem Pembangkit Tenaga Uap','Toto Hardianto','Teknik Mesin',5);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('MS4031','Perancangan Sistem Fluida','I Nengah Diasta','Teknik Mesin',18);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('MS4032','Sistem Pendingan dan Kriogenikas','Ari Darmawan Pasek','Teknik Mesin',22);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('MS4033','Motor Bakar Torak','Iman Kartolaksono Reksowardojo','Teknik Mesin',12);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('MS4034','Turbin Gas','Tri Yuswidjajanto Zaenuri','Teknik Mesin',31);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('AE2100','Pengenalan Teknik Dirgantara','Hari Muhammad','Teknik Dirgantara',98);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('AE2101','Matematika Teknik I','Mochammad Agoes Moelyadi','Teknik Dirgantara',94);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('AE2102','Rekayasa Termal','Lavi Rizki Zuhal','Teknik Dirgantara',92);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('AE2103','Kinematika dan Dinamika','Leonardo Gunawan','Teknik Dirgantara',92);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('AE2150','Material Pesawat dan Metode Manufaktur I','Sigit Puji Santosa','Teknik Dirgantara',94);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('AE3110','Aerodinamika I','Djoko Sardjadi','Teknik Dirgantara',56);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('AE3111','Analisis Aerodinamika dan Prestasi Terbang II','Ony Arifianto','Teknik Dirgantara',56);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('AE3180','Sistem Pesawat Udara I','Edy Suwondo','Teknik Dirgantara',58);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('AE4010','Aerodinamika Komputasi','Mochammad Agoes Moelyadi','Teknik Dirgantara',9);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('AE4030','Dinamika dan Pengendalian Satelit','Ridanto Eko Poetro','Teknik Dirgantara',11);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('MT2101','Sifat Mekanik Material','Arif Basuki','Teknik Material',70);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('MT2102','Mekanika Material','Hermawan Judawisastra','Teknik Material',69);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('MT3114','Transformasi Fasa','Rochim Suratman','Teknik Material',77);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('MT3132','Material Polimer','Mardiyanti','Teknik Material',77);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('MT4033','Proses Pengerjaan Komposit Polimer','Slameto','Teknik Material',80);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('SI2011','Rekayasa Bahan Konstruksi Sipil','Herlien Dwiarti Soemari','Teknik Sipil',200);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('SI2012','Analisis Statistik dan Probabilitas','Hernawan Mahfudz','Teknik Sipil',160);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('SI2131','Mekanika Fluida dan Hidraulika','Arno Adi Kuntoro','Teknik Sipil',160);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('SI3112','Struktur Beton','Indra Djati','Teknik Sipil',165);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('SI3121','Mekanika Tanah II','Franciscus Xaverius Toha','Teknik Sipil',154);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('SI3131','Irigasi dan Drainase','Sri Legowo Wignyo Darsono','Teknik Sipil',163);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('SI4111','Rekayasa & Perancangan Struktur','Made Suarjana','Teknik Sipil',161);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('SI4112','Struktur Beton Lanjut','Iswandi Irman','Teknik Sipil',135);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('SI4151','Ekonomi Teknik','N.R. Reini Djuhraeni W.','Teknik Sipil',166);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('TL2104','Pengantar Teknik Lingkungan','Qomarudin Helmy','Teknik Lingkungan',107);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('TL3101','Pengolahan Fisik dan Kimia','Marisa Handajani','Teknik Lingkungan',89);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('TL3104','Pengelolaan Persampahan','Mochammad Chaerul','Teknik Lingkungan',38);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('TL3105','Teknik Penyediaan Air Minum','Yuniati','Teknik Lingkungan',84);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('TL4002','Rekayasa Lingkungan','Arief Sudradjat','Teknik Lingkungan',171);
INSERT INTO Courses(ID_Course,Course_Name,Lecturer,Topic,Attendance) VALUES ('TL4103','Kesehatan Lingkungan Kerja','Katharina Oginawati','Teknik Lingkungan',117);
